services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - blue
      - green

  blue:
    image: yimikaade/wonderful:devops-stage-two
    container_name: blue
    ports:
      - "8081:8081"
    restart: on-failure
  green:
    image: yimikaade/wonderful:devops-stage-two
    container_name: green
    ports:
      - "8082:8082"
    restart: on-failure
    
