services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - blue
      - green

  blue:
    image: ${BLUE_IMAGE}
    container_name: blue
    ports:
      - "8081:4000"
    environment:
      - PORT=${PORT_BLUE}
      - APP_POOL=${ACTIVE_POOL_BLUE}
      - RELEASE_ID=${RELEASE_ID_BLUE}
  green:
    image: ${GREEN_IMAGE}
    container_name: green
    ports:
      - "8082:5000"
    environment:
      - PORT=${PORT_GREEN}
      - APP_POOL=${ACTIVE_POOL_GREEN}
      - RELEASE_ID=${RELEASE_ID_GREEN}
    
